
[options]
addons_path = odoo/addons,custom_addons,C:\Users\Sarita\odoo16_proyecto\server-auth,C:\Users\Sarita\odoo16_proyecto\rest-framework
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
#para jwt
jwt_secret = MiClaveJWTsuperSegura123
jwt_algorithm = HS256
jwt_expiration = 3600

# Claves que sí lee auth_jwt en v16:
auth_jwt.check_session = False
auth_jwt.header = Authorization
auth_jwt.prefix = Bearer

